<?php

namespace DW\ComReminderBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * RemindRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RemindRepository extends EntityRepository
{
}
