parameters:
#    dw_com_reminder.example.class: DW\ComReminderBundle\Example

services:
#    dw_com_reminder.example:
#        class: %dw_com_reminder.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
